# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            SAENi7 Video Archive
tagline:          'I made this because shit happens.'
description:      'I made this because shit happens. This is my <a href="https://www.youtube.com/channel/UCrJU4svIgCbX-AVc-JaKz4A" target="_blank">YouTube</a>, and this is my <a href="https://twitter.com/SAENiJP" target="_blank">Twitter.</a>'
baseurl:          /

author:
  name:           'SAENi7'
  url:            https://twitter.com/SAENiJP

paginate:         5

# Custom vars
version:          SAENi7Archive

