# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            SAENi7 Video Archive
tagline:          'I made this because shit happens.'
description:      'I made this because shit happens.'
baseurl:          /

author:
  name:           'SAENi7'
  url:            https://twitter.com/SAENiJP

paginate:         5

# Custom vars
version:          SAENi7Archive

